### ISSUE TITLE
Create some base seeders

### ISSUE THREAD

**Issue by Morkhusz** [brunobandev/veganation#27]
@brunobandev 
It would be nice if we could run a seed command and have a fully functional application.

To achieve this some seeders need to be created, for example:
- [x] A `Categories` seeder
- [x] A `Recipes` seeder with at least one recipe related with a category created on the category seeder

So anyone who wants to contribute with the project can have some samples to work with.

I can help with this if needed =)

**Comment by brunobandev** [comment]
Sure, I will do this!

**Comment by brunobandev** [comment]
Done!
